<?php

namespace App\Console\Commands;

use App\Jobs\Raiida\ExtractConjugaisonLessonsJob;
use App\Services\Raiida\ConjugaisonExtractionService;
use Illuminate\Console\Command;

class RevizySeederExtractConjugaisonCommand extends Command
{
    protected $signature = 'revizyseeder:extract-conjugaison
        {--force : Replace existing N/P/SEM entries generated by extraction}
        {--queue : Dispatch extraction as queue job}';

    protected $description = 'Extract conjugaison lessons from presentation_data JSON and persist N/P/SEM entries.';

    public function handle(ConjugaisonExtractionService $service): int
    {
        $this->call('app:db-backup');
        $force = (bool) $this->option('force');

        if ((bool) $this->option('queue')) {
            $user = auth()->user();

            ExtractConjugaisonLessonsJob::dispatch(
                $force,
                null,
                $user?->id,
                $user?->email,
                $user?->role
            );

            $this->info('Conjugaison extraction job queued.');
            $this->line('Queue: ' . (string) config('raiida.conjugaison_extraction.queue', 'revizyseeder-workflows'));

            return self::SUCCESS;
        }

        $summary = $service->run($force);

        $this->table(
            ['Metric', 'Value'],
            [
                ['Assets scanned', (string) ($summary['assets_scanned'] ?? 0)],
                ['Assets qualified', (string) ($summary['assets_qualified'] ?? 0)],
                ['Assets with JSON', (string) ($summary['assets_with_json'] ?? 0)],
                ['Candidates found', (string) ($summary['candidates_found'] ?? 0)],
                ['Question candidates', (string) ($summary['question_candidates_found'] ?? 0)],
                ['N/P/SEM keys detected', (string) ($summary['keys_detected'] ?? 0)],
                ['Coverage total', (string) ($summary['coverage_total'] ?? 0)],
                ['Persisted lessons', (string) ($summary['persisted'] ?? 0)],
                ['Placeholders created', (string) ($summary['placeholders_created'] ?? 0)],
                ['Questions attached', (string) ($summary['questions_attached'] ?? 0)],
                ['Skipped missing JSON', (string) ($summary['skipped_missing_json'] ?? 0)],
                ['Skipped invalid JSON', (string) ($summary['skipped_invalid_json'] ?? 0)],
            ]
        );

        $this->info('Conjugaison extraction completed.');

        return self::SUCCESS;
    }
}
